<?xml version="1.0" encoding="utf-8"?><Database Name="DB_9CBDC5_campus2caretaker" Class="Campus2CaretakerDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=SQL5009.myASP.NET;Initial Catalog=DB_9CBDC5_campus2caretaker;Persist Security Info=True;User ID=DB_9CBDC5_campus2caretaker_admin" SettingsObjectName="DataAccessObject.Properties.Settings" SettingsPropertyName="DB_9CBDC5_campus2caretakerConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblSuperAdminLogin" Member="tblSuperAdminLogins">
    <Type Name="tblSuperAdminLogin">
      <Column Name="colUsername" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="colPassword" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tblInstituteLogin" Member="tblInstituteLogins">
    <Type Name="tblInstituteLogin">
      <Column Name="colUsername" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="colPassword" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="colUserType" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="colInstituteId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="tblInstituteDetail_tblInstituteLogin" Member="tblInstituteDetail" ThisKey="colInstituteId" OtherKey="colInstituteId" Type="tblInstituteDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblInstituteDetails" Member="tblInstituteDetails">
    <Type Name="tblInstituteDetail">
      <Column Name="colInstituteId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="colInstituteName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="colAddress" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="colPhone" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="colLogoPath" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="colPrincipalName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="colPrincipalContact" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="colInstituteType" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="colState" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="colDistrict" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="colSecondLineAddress" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="tblInstituteDetail_tblInstituteLogin" Member="tblInstituteLogins" ThisKey="colInstituteId" OtherKey="colInstituteId" Type="tblInstituteLogin" />
      <Association Name="tblInstituteDetail_tblBranchDetail" Member="tblBranchDetails" ThisKey="colInstituteId" OtherKey="colInstituteId" Type="tblBranchDetail" />
      <Association Name="tblInstituteDetail_tblSubjectDetail" Member="tblSubjectDetails" ThisKey="colInstituteId" OtherKey="colInstituteId" Type="tblSubjectDetail" />
      <Association Name="tblInstituteDetail_tblInternalMark" Member="tblInternalMarks" ThisKey="colInstituteId" OtherKey="colInstituteId" Type="tblInternalMark" />
      <Association Name="tblInstituteDetail_tblAttendanceDetail" Member="tblAttendanceDetails" ThisKey="colInstituteId" OtherKey="colInstituteId" Type="tblAttendanceDetail" />
    </Type>
  </Table>
  <Table Name="dbo.tblBranchDetails" Member="tblBranchDetails">
    <Type Name="tblBranchDetail">
      <Column Name="colBranchId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="colBranchName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="colInstituteId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="colHeadofBranch" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="colHeadofBranchContact" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="tblInstituteDetail_tblBranchDetail" Member="tblInstituteDetail" ThisKey="colInstituteId" OtherKey="colInstituteId" Type="tblInstituteDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblSubjectDetails" Member="tblSubjectDetails">
    <Type Name="tblSubjectDetail">
      <Column Name="colSubjectId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="colSemester" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="colBranchId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colSubjectName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="colIsTheory" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="colInstituteId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tblInstituteDetail_tblSubjectDetail" Member="tblInstituteDetail" ThisKey="colInstituteId" OtherKey="colInstituteId" Type="tblInstituteDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblStudentDetails" Member="tblStudentDetails">
    <Type Name="tblStudentDetail">
      <Column Name="colStudentId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="colStudentName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="colLastName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="colFatherName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="colMotherName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="colDOB" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="colSemesterId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colBranchId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colSection" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="colRollNo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="colParentsMobileNo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="colInstituteId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colAddress" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="tblStudentDetail_tblAttendanceDetail" Member="tblAttendanceDetails" ThisKey="colStudentId" OtherKey="colStudentId" Type="tblAttendanceDetail" />
    </Type>
  </Table>
  <Table Name="dbo.tblInternalMarks" Member="tblInternalMarks">
    <Type Name="tblInternalMark">
      <Column Name="colInternalsEntryId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="colStudentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colBranchId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colSection" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="colSemesterId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colInternals" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="colMonth" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="colYear" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="colInstituteId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colMaxMarks" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="colMinMarks" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="colMarksScored" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Association Name="tblInstituteDetail_tblInternalMark" Member="tblInstituteDetail" ThisKey="colInstituteId" OtherKey="colInstituteId" Type="tblInstituteDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblAttendanceDetails" Member="tblAttendanceDetails">
    <Type Name="tblAttendanceDetail">
      <Column Name="colAttendanceEntryId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="colStudentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colBranchId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colSemesterId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colSection" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="colMonth" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="colYear" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colInstituteId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colClassesHeldMonth" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="colClassesAttendedMonth" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="colClassesAttendedMonthPercent" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="colAccumulatedClassesHeld" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="colAccumulatedClassesAttended" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="colAccumulatedClassesAttendedPercent" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Association Name="tblInstituteDetail_tblAttendanceDetail" Member="tblInstituteDetail" ThisKey="colInstituteId" OtherKey="colInstituteId" Type="tblInstituteDetail" IsForeignKey="true" />
      <Association Name="tblStudentDetail_tblAttendanceDetail" Member="tblStudentDetail" ThisKey="colStudentId" OtherKey="colStudentId" Type="tblStudentDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.GetInstituteDetails" Method="GetInstituteDetails">
    <Parameter Name="instituteid" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetInstituteDetailsResult">
      <Column Name="colInstitutename" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="colAddress" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="colPhone" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="colLogoPath" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="colPrincipalName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="colPrincipalContact" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="colInstituteType" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="colUsername" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="colDistrict" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="colState" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetStudentDetails" Method="GetStudentDetails">
    <Parameter Name="studentid" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetStudentDetailsResult">
      <Column Name="colStudentName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="colLastName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="colFatherName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="colMotherName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="colDOB" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="colSemesterId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colBranchId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colSection" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="colRollNo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="colParentsMobileNo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="colInstituteId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colAddress" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetStudentsInternalsDetails" Method="GetStudentsInternalsDetails">
    <Parameter Name="instituteid" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetStudentsInternalsDetailsResult">
      <Column Name="colInternals" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="colMonth" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="colYear" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="colMaxMarks" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="colMinMarks" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="colMarksScored" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="colStudentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="colStudentName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="colSemesterId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="colBranchId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="colSection" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="colRollNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetStudentsAttendanceDetails" Method="GetStudentsAttendanceDetails">
    <Parameter Name="instituteid" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetStudentsAttendanceDetailsResult">
      <Column Name="colMonth" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="colYear" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colClassesHeldMonth" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="colClassesAttendedMonth" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="colClassesAttendedMonthPercent" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="colAccumulatedClassesHeld" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="colAccumulatedClassesAttended" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="colAccumulatedClassesAttendedPercent" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="colStudentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="colStudentName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="colSemesterId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="colBranchId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="colSection" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="colRollNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>