<?xml version="1.0" encoding="utf-8"?><Database Name="c2c" Class="Campus2CaretakerDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=wp.cronnet.co.in;Initial Catalog=c2c;Persist Security Info=True;User ID=raghavak" SettingsObjectName="DataAccessObject.Properties.Settings" SettingsPropertyName="DB_9CBDC5_campus2caretakerConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblSuperAdminLogin" Member="tblSuperAdminLogins">
    <Type Name="tblSuperAdminLogin">
      <Column Name="colUsername" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="colPassword" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tblInstituteLogin" Member="tblInstituteLogins">
    <Type Name="tblInstituteLogin">
      <Column Name="colUsername" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="colPassword" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="colUserType" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="colInstituteId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="tblInstituteDetail_tblInstituteLogin" Member="tblInstituteDetail" ThisKey="colInstituteId" OtherKey="colInstituteId" Type="tblInstituteDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblBranchDetails" Member="tblBranchDetails">
    <Type Name="tblBranchDetail">
      <Column Name="colBranchId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="colBranchName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="colInstituteId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="colHeadofBranch" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="colHeadofBranchContact" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="tblInstituteDetail_tblBranchDetail" Member="tblInstituteDetail" ThisKey="colInstituteId" OtherKey="colInstituteId" Type="tblInstituteDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblSubjectDetails" Member="tblSubjectDetails">
    <Type Name="tblSubjectDetail">
      <Column Name="colSubjectId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="colSemester" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="colBranchId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colSubjectName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="colIsTheory" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="colInstituteId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tblInstituteDetail_tblSubjectDetail" Member="tblInstituteDetail" ThisKey="colInstituteId" OtherKey="colInstituteId" Type="tblInstituteDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblSMSTemplates" Member="tblSMSTemplates">
    <Type Name="tblSMSTemplate">
      <Column Name="TemplateType" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Template" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tblAttendanceDetails" Member="tblAttendanceDetails">
    <Type Name="tblAttendanceDetail">
      <Column Name="colAttendanceEntryId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="colStudentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colBranchId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colSemesterId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colSection" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="colMonth" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="colYear" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colInstituteId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colClassesHeldMonth" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="colClassesAttendedMonth" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="colClassesAttendedMonthPercent" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="colAccumulatedClassesHeld" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="colAccumulatedClassesAttended" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="colAccumulatedClassesAttendedPercent" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="colSubjectId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colDescription" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="colRemarks" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="tblStudentDetail_tblAttendanceDetail" Member="tblStudentDetail" ThisKey="colStudentId" OtherKey="colStudentId" Type="tblStudentDetail" IsForeignKey="true" />
      <Association Name="tblInstituteDetail_tblAttendanceDetail" Member="tblInstituteDetail" ThisKey="colInstituteId" OtherKey="colInstituteId" Type="tblInstituteDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblInternalMarks" Member="tblInternalMarks">
    <Type Name="tblInternalMark">
      <Column Name="colInternalsEntryId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="colStudentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colBranchId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colSection" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="colSemesterId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colInternals" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="colMonth" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="colYear" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="colInstituteId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colMaxMarks" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="colMinMarks" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="colMarksScored" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="colSubjectId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="colRemarks" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="colDescription" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="tblInstituteDetail_tblInternalMark" Member="tblInstituteDetail" ThisKey="colInstituteId" OtherKey="colInstituteId" Type="tblInstituteDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblStudentDetails" Member="tblStudentDetails">
    <Type Name="tblStudentDetail">
      <Column Name="colStudentId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="colStudentName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="colLastName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="colFatherName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="colMotherName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="colDOB" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="colSemesterId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colBranchId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colSection" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="colRollNo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="colParentsMobileNo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="colInstituteId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colAddress" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="colParentsEmail" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="colGender" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="tblStudentDetail_tblAttendanceDetail" Member="tblAttendanceDetails" ThisKey="colStudentId" OtherKey="colStudentId" Type="tblAttendanceDetail" />
    </Type>
  </Table>
  <Table Name="dbo.tblInstituteDetails" Member="tblInstituteDetails">
    <Type Name="tblInstituteDetail">
      <Column Name="colInstituteId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="colInstituteName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="colAddress" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="colPhone" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="colLogoPath" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="colPrincipalName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="colPrincipalContact" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="colInstituteType" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="colState" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="colDistrict" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="colSecondLineAddress" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="colMaxStudents" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="tblInstituteDetail_tblInstituteLogin" Member="tblInstituteLogins" ThisKey="colInstituteId" OtherKey="colInstituteId" Type="tblInstituteLogin" />
      <Association Name="tblInstituteDetail_tblBranchDetail" Member="tblBranchDetails" ThisKey="colInstituteId" OtherKey="colInstituteId" Type="tblBranchDetail" />
      <Association Name="tblInstituteDetail_tblSubjectDetail" Member="tblSubjectDetails" ThisKey="colInstituteId" OtherKey="colInstituteId" Type="tblSubjectDetail" />
      <Association Name="tblInstituteDetail_tblAttendanceDetail" Member="tblAttendanceDetails" ThisKey="colInstituteId" OtherKey="colInstituteId" Type="tblAttendanceDetail" />
      <Association Name="tblInstituteDetail_tblInternalMark" Member="tblInternalMarks" ThisKey="colInstituteId" OtherKey="colInstituteId" Type="tblInternalMark" />
    </Type>
  </Table>
  <Function Name="dbo.GetBarChartInternalsDetails" Method="GetBarChartInternalsDetails">
    <Parameter Name="instituteid" Type="System.Int32" DbType="Int" />
    <Parameter Name="month" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="year" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetBarChartInternalsDetailsResult">
      <Column Name="colMarksScored" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="colSubjectId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colSubjectName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="colBranchId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colBranchName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetStudentsAttendanceDetailsEdit" Method="GetStudentsAttendanceDetailsEdit">
    <Parameter Name="instituteid" Type="System.Int32" DbType="Int" />
    <Parameter Name="colSubjectId" Type="System.Int32" DbType="Int" />
    <Parameter Name="colMonth" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="colYear" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="colSemester" Type="System.Int32" DbType="Int" />
    <Parameter Name="colBranchId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetStudentsAttendanceDetailsEditResult">
      <Column Name="colClassesHeldMonth" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="colClassesAttendedMonth" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="colClassesAttendedMonthPercent" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="colAccumulatedClassesHeld" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="colAccumulatedClassesAttended" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="colAccumulatedClassesAttendedPercent" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="colStudentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colStudentName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="colSemesterId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colBranchId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colSection" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="colRollNo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="colSubjectId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colMonth" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="colYear" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colRemarks" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="colDescription" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetStudentsAttendanceDetailsNewEntry" Method="GetStudentsAttendanceDetailsNewEntry">
    <Parameter Name="instituteid" Type="System.Int32" DbType="Int" />
    <Parameter Name="colSubjectId" Type="System.Int32" DbType="Int" />
    <Parameter Name="colMonth" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="colYear" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="colSemester" Type="System.Int32" DbType="Int" />
    <Parameter Name="colBranchId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetStudentsAttendanceDetailsNewEntryResult">
      <Column Name="colClassesHeldMonth" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colClassesAttendedMonth" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colClassesAttendedMonthPercent" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colAccumulatedClassesHeld" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colAccumulatedClassesAttended" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colAccumulatedClassesAttendedPercent" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colStudentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colStudentName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="colSemesterId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colBranchId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colSection" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="colRollNo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="colRemarks" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="colDescription" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetStudentsInternalsDetailsEdit" Method="GetStudentsInternalsDetailsEdit">
    <Parameter Name="instituteid" Type="System.Int32" DbType="Int" />
    <Parameter Name="colSubjectId" Type="System.Int32" DbType="Int" />
    <Parameter Name="colMonth" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="colYear" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="colSemester" Type="System.Int32" DbType="Int" />
    <Parameter Name="colBranchId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetStudentsInternalsDetailsEditResult">
      <Column Name="colMaxMarks" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="colMinMarks" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="colMarksScored" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="colStudentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colStudentName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="colSemesterId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colBranchId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colSection" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="colRollNo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="colSubjectId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="colMonth" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="colYear" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="colRemarks" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="colDescription" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetStudentsInternalsDetailsNewEntry" Method="GetStudentsInternalsDetailsNewEntry">
    <Parameter Name="instituteid" Type="System.Int32" DbType="Int" />
    <Parameter Name="colSubjectId" Type="System.Int32" DbType="Int" />
    <Parameter Name="colMonth" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="colYear" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="colSemester" Type="System.Int32" DbType="Int" />
    <Parameter Name="colBranchId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetStudentsInternalsDetailsNewEntryResult">
      <Column Name="colMaxMarks" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colMinMarks" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colMarksScored" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colStudentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colStudentName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="colSemesterId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colBranchId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colSection" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="colRollNo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="colRemarks" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="colDescription" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetStudentDetails" Method="GetStudentDetails">
    <Parameter Name="studentid" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetStudentDetailsResult">
      <Column Name="colStudentName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="colLastName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="colFatherName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="colMotherName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="colDOB" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="colSemesterId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colBranchId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colSection" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="colRollNo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="colParentsMobileNo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="colInstituteId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colAddress" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="colParentsEmail" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="colGender" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetStudentCount" Method="GetStudentCount">
    <Parameter Name="instituteid" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetStudentCountResult">
      <Column Name="TotalCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetStudentCountClasswiseGender" Method="GetStudentCountClasswiseGender">
    <Parameter Name="instituteid" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetStudentCountClasswiseGenderResult">
      <Column Name="TotalCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="colBranchId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="colBranchName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetStudentsAttendanceDetailsMonthwise" Method="GetStudentsAttendanceDetailsMonthwise">
    <Parameter Name="instituteid" Type="System.Int32" DbType="Int" />
    <Parameter Name="colMonth" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="colYear" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="GetStudentsAttendanceDetailsMonthwiseResult">
      <Column Name="AttendanceCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="colBranchId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="colSemesterId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="columnname" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="colBranchName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetStudentsMarksDetailsMonthwise" Method="GetStudentsMarksDetailsMonthwise">
    <Parameter Name="instituteid" Type="System.Int32" DbType="Int" />
    <Parameter Name="colMonth" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="colYear" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="GetStudentsMarksDetailsMonthwiseResult">
      <Column Name="MarksScoredCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="colBranchId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="colSemesterId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="colSubjectId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="columnname" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="colBranchName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="colSubjectName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetInstituteDetails" Method="GetInstituteDetails">
    <Parameter Name="instituteid" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetInstituteDetailsResult">
      <Column Name="colInstitutename" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="colAddress" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="colPhone" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="colLogoPath" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="colPrincipalName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="colPrincipalContact" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="colInstituteType" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="colUsername" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="colDistrict" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="colState" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="colMaxStudents" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>