#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessObject
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_9CBDC5_campus2caretaker")]
	public partial class Campus2CaretakerDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblSuperAdminLogin(tblSuperAdminLogin instance);
    partial void UpdatetblSuperAdminLogin(tblSuperAdminLogin instance);
    partial void DeletetblSuperAdminLogin(tblSuperAdminLogin instance);
    partial void InserttblInstituteLogin(tblInstituteLogin instance);
    partial void UpdatetblInstituteLogin(tblInstituteLogin instance);
    partial void DeletetblInstituteLogin(tblInstituteLogin instance);
    partial void InserttblInstituteDetail(tblInstituteDetail instance);
    partial void UpdatetblInstituteDetail(tblInstituteDetail instance);
    partial void DeletetblInstituteDetail(tblInstituteDetail instance);
    partial void InserttblClassDetail(tblClassDetail instance);
    partial void UpdatetblClassDetail(tblClassDetail instance);
    partial void DeletetblClassDetail(tblClassDetail instance);
    #endregion
		
		public Campus2CaretakerDataContext() : 
				base(global::DataAccessObject.Properties.Settings.Default.DB_9CBDC5_campus2caretakerConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Campus2CaretakerDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Campus2CaretakerDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Campus2CaretakerDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Campus2CaretakerDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblSuperAdminLogin> tblSuperAdminLogins
		{
			get
			{
				return this.GetTable<tblSuperAdminLogin>();
			}
		}
		
		public System.Data.Linq.Table<tblInstituteLogin> tblInstituteLogins
		{
			get
			{
				return this.GetTable<tblInstituteLogin>();
			}
		}
		
		public System.Data.Linq.Table<tblInstituteDetail> tblInstituteDetails
		{
			get
			{
				return this.GetTable<tblInstituteDetail>();
			}
		}
		
		public System.Data.Linq.Table<tblClassDetail> tblClassDetails
		{
			get
			{
				return this.GetTable<tblClassDetail>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetInstituteDetails")]
		public ISingleResult<GetInstituteDetailsResult> GetInstituteDetails([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> instituteid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), instituteid);
			return ((ISingleResult<GetInstituteDetailsResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblSuperAdminLogin")]
	public partial class tblSuperAdminLogin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _colUsername;
		
		private string _colPassword;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncolUsernameChanging(string value);
    partial void OncolUsernameChanged();
    partial void OncolPasswordChanging(string value);
    partial void OncolPasswordChanged();
    #endregion
		
		public tblSuperAdminLogin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_colUsername", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string colUsername
		{
			get
			{
				return this._colUsername;
			}
			set
			{
				if ((this._colUsername != value))
				{
					this.OncolUsernameChanging(value);
					this.SendPropertyChanging();
					this._colUsername = value;
					this.SendPropertyChanged("colUsername");
					this.OncolUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_colPassword", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string colPassword
		{
			get
			{
				return this._colPassword;
			}
			set
			{
				if ((this._colPassword != value))
				{
					this.OncolPasswordChanging(value);
					this.SendPropertyChanging();
					this._colPassword = value;
					this.SendPropertyChanged("colPassword");
					this.OncolPasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblInstituteLogin")]
	public partial class tblInstituteLogin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _colUsername;
		
		private string _colPassword;
		
		private string _colUserType;
		
		private int _colInstituteId;
		
		private EntityRef<tblInstituteDetail> _tblInstituteDetail;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncolUsernameChanging(string value);
    partial void OncolUsernameChanged();
    partial void OncolPasswordChanging(string value);
    partial void OncolPasswordChanged();
    partial void OncolUserTypeChanging(string value);
    partial void OncolUserTypeChanged();
    partial void OncolInstituteIdChanging(int value);
    partial void OncolInstituteIdChanged();
    #endregion
		
		public tblInstituteLogin()
		{
			this._tblInstituteDetail = default(EntityRef<tblInstituteDetail>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_colUsername", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string colUsername
		{
			get
			{
				return this._colUsername;
			}
			set
			{
				if ((this._colUsername != value))
				{
					this.OncolUsernameChanging(value);
					this.SendPropertyChanging();
					this._colUsername = value;
					this.SendPropertyChanged("colUsername");
					this.OncolUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_colPassword", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string colPassword
		{
			get
			{
				return this._colPassword;
			}
			set
			{
				if ((this._colPassword != value))
				{
					this.OncolPasswordChanging(value);
					this.SendPropertyChanging();
					this._colPassword = value;
					this.SendPropertyChanged("colPassword");
					this.OncolPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_colUserType", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string colUserType
		{
			get
			{
				return this._colUserType;
			}
			set
			{
				if ((this._colUserType != value))
				{
					this.OncolUserTypeChanging(value);
					this.SendPropertyChanging();
					this._colUserType = value;
					this.SendPropertyChanged("colUserType");
					this.OncolUserTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_colInstituteId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int colInstituteId
		{
			get
			{
				return this._colInstituteId;
			}
			set
			{
				if ((this._colInstituteId != value))
				{
					if (this._tblInstituteDetail.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncolInstituteIdChanging(value);
					this.SendPropertyChanging();
					this._colInstituteId = value;
					this.SendPropertyChanged("colInstituteId");
					this.OncolInstituteIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblInstituteDetail_tblInstituteLogin", Storage="_tblInstituteDetail", ThisKey="colInstituteId", OtherKey="colInstituteId", IsForeignKey=true)]
		public tblInstituteDetail tblInstituteDetail
		{
			get
			{
				return this._tblInstituteDetail.Entity;
			}
			set
			{
				tblInstituteDetail previousValue = this._tblInstituteDetail.Entity;
				if (((previousValue != value) 
							|| (this._tblInstituteDetail.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblInstituteDetail.Entity = null;
						previousValue.tblInstituteLogins.Remove(this);
					}
					this._tblInstituteDetail.Entity = value;
					if ((value != null))
					{
						value.tblInstituteLogins.Add(this);
						this._colInstituteId = value.colInstituteId;
					}
					else
					{
						this._colInstituteId = default(int);
					}
					this.SendPropertyChanged("tblInstituteDetail");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblInstituteDetails")]
	public partial class tblInstituteDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _colInstituteId;
		
		private string _colInstituteName;
		
		private string _colAddress;
		
		private string _colPhone;
		
		private string _colLogoPath;
		
		private string _colPrincipalName;
		
		private string _colPrincipalContact;
		
		private string _colInstituteType;
		
		private string _colState;
		
		private string _colDistrict;
		
		private string _colSecondLineAddress;
		
		private EntitySet<tblInstituteLogin> _tblInstituteLogins;
		
		private EntitySet<tblClassDetail> _tblClassDetails;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncolInstituteIdChanging(int value);
    partial void OncolInstituteIdChanged();
    partial void OncolInstituteNameChanging(string value);
    partial void OncolInstituteNameChanged();
    partial void OncolAddressChanging(string value);
    partial void OncolAddressChanged();
    partial void OncolPhoneChanging(string value);
    partial void OncolPhoneChanged();
    partial void OncolLogoPathChanging(string value);
    partial void OncolLogoPathChanged();
    partial void OncolPrincipalNameChanging(string value);
    partial void OncolPrincipalNameChanged();
    partial void OncolPrincipalContactChanging(string value);
    partial void OncolPrincipalContactChanged();
    partial void OncolInstituteTypeChanging(string value);
    partial void OncolInstituteTypeChanged();
    partial void OncolStateChanging(string value);
    partial void OncolStateChanged();
    partial void OncolDistrictChanging(string value);
    partial void OncolDistrictChanged();
    partial void OncolSecondLineAddressChanging(string value);
    partial void OncolSecondLineAddressChanged();
    #endregion
		
		public tblInstituteDetail()
		{
			this._tblInstituteLogins = new EntitySet<tblInstituteLogin>(new Action<tblInstituteLogin>(this.attach_tblInstituteLogins), new Action<tblInstituteLogin>(this.detach_tblInstituteLogins));
			this._tblClassDetails = new EntitySet<tblClassDetail>(new Action<tblClassDetail>(this.attach_tblClassDetails), new Action<tblClassDetail>(this.detach_tblClassDetails));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_colInstituteId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int colInstituteId
		{
			get
			{
				return this._colInstituteId;
			}
			set
			{
				if ((this._colInstituteId != value))
				{
					this.OncolInstituteIdChanging(value);
					this.SendPropertyChanging();
					this._colInstituteId = value;
					this.SendPropertyChanged("colInstituteId");
					this.OncolInstituteIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_colInstituteName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string colInstituteName
		{
			get
			{
				return this._colInstituteName;
			}
			set
			{
				if ((this._colInstituteName != value))
				{
					this.OncolInstituteNameChanging(value);
					this.SendPropertyChanging();
					this._colInstituteName = value;
					this.SendPropertyChanged("colInstituteName");
					this.OncolInstituteNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_colAddress", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string colAddress
		{
			get
			{
				return this._colAddress;
			}
			set
			{
				if ((this._colAddress != value))
				{
					this.OncolAddressChanging(value);
					this.SendPropertyChanging();
					this._colAddress = value;
					this.SendPropertyChanged("colAddress");
					this.OncolAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_colPhone", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string colPhone
		{
			get
			{
				return this._colPhone;
			}
			set
			{
				if ((this._colPhone != value))
				{
					this.OncolPhoneChanging(value);
					this.SendPropertyChanging();
					this._colPhone = value;
					this.SendPropertyChanged("colPhone");
					this.OncolPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_colLogoPath", DbType="VarChar(50)")]
		public string colLogoPath
		{
			get
			{
				return this._colLogoPath;
			}
			set
			{
				if ((this._colLogoPath != value))
				{
					this.OncolLogoPathChanging(value);
					this.SendPropertyChanging();
					this._colLogoPath = value;
					this.SendPropertyChanged("colLogoPath");
					this.OncolLogoPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_colPrincipalName", DbType="VarChar(50)")]
		public string colPrincipalName
		{
			get
			{
				return this._colPrincipalName;
			}
			set
			{
				if ((this._colPrincipalName != value))
				{
					this.OncolPrincipalNameChanging(value);
					this.SendPropertyChanging();
					this._colPrincipalName = value;
					this.SendPropertyChanged("colPrincipalName");
					this.OncolPrincipalNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_colPrincipalContact", DbType="NVarChar(50)")]
		public string colPrincipalContact
		{
			get
			{
				return this._colPrincipalContact;
			}
			set
			{
				if ((this._colPrincipalContact != value))
				{
					this.OncolPrincipalContactChanging(value);
					this.SendPropertyChanging();
					this._colPrincipalContact = value;
					this.SendPropertyChanged("colPrincipalContact");
					this.OncolPrincipalContactChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_colInstituteType", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string colInstituteType
		{
			get
			{
				return this._colInstituteType;
			}
			set
			{
				if ((this._colInstituteType != value))
				{
					this.OncolInstituteTypeChanging(value);
					this.SendPropertyChanging();
					this._colInstituteType = value;
					this.SendPropertyChanged("colInstituteType");
					this.OncolInstituteTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_colState", DbType="VarChar(50)")]
		public string colState
		{
			get
			{
				return this._colState;
			}
			set
			{
				if ((this._colState != value))
				{
					this.OncolStateChanging(value);
					this.SendPropertyChanging();
					this._colState = value;
					this.SendPropertyChanged("colState");
					this.OncolStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_colDistrict", DbType="VarChar(50)")]
		public string colDistrict
		{
			get
			{
				return this._colDistrict;
			}
			set
			{
				if ((this._colDistrict != value))
				{
					this.OncolDistrictChanging(value);
					this.SendPropertyChanging();
					this._colDistrict = value;
					this.SendPropertyChanged("colDistrict");
					this.OncolDistrictChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_colSecondLineAddress", DbType="VarChar(MAX)")]
		public string colSecondLineAddress
		{
			get
			{
				return this._colSecondLineAddress;
			}
			set
			{
				if ((this._colSecondLineAddress != value))
				{
					this.OncolSecondLineAddressChanging(value);
					this.SendPropertyChanging();
					this._colSecondLineAddress = value;
					this.SendPropertyChanged("colSecondLineAddress");
					this.OncolSecondLineAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblInstituteDetail_tblInstituteLogin", Storage="_tblInstituteLogins", ThisKey="colInstituteId", OtherKey="colInstituteId")]
		public EntitySet<tblInstituteLogin> tblInstituteLogins
		{
			get
			{
				return this._tblInstituteLogins;
			}
			set
			{
				this._tblInstituteLogins.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblInstituteDetail_tblClassDetail", Storage="_tblClassDetails", ThisKey="colInstituteId", OtherKey="colInstituteId")]
		public EntitySet<tblClassDetail> tblClassDetails
		{
			get
			{
				return this._tblClassDetails;
			}
			set
			{
				this._tblClassDetails.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblInstituteLogins(tblInstituteLogin entity)
		{
			this.SendPropertyChanging();
			entity.tblInstituteDetail = this;
		}
		
		private void detach_tblInstituteLogins(tblInstituteLogin entity)
		{
			this.SendPropertyChanging();
			entity.tblInstituteDetail = null;
		}
		
		private void attach_tblClassDetails(tblClassDetail entity)
		{
			this.SendPropertyChanging();
			entity.tblInstituteDetail = this;
		}
		
		private void detach_tblClassDetails(tblClassDetail entity)
		{
			this.SendPropertyChanging();
			entity.tblInstituteDetail = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblClassDetails")]
	public partial class tblClassDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _colClassId;
		
		private string _colClassName;
		
		private int _colInstituteId;
		
		private string _colHeadofClass;
		
		private string _colHeadofClassContact;
		
		private EntityRef<tblInstituteDetail> _tblInstituteDetail;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncolClassIdChanging(int value);
    partial void OncolClassIdChanged();
    partial void OncolClassNameChanging(string value);
    partial void OncolClassNameChanged();
    partial void OncolInstituteIdChanging(int value);
    partial void OncolInstituteIdChanged();
    partial void OncolHeadofClassChanging(string value);
    partial void OncolHeadofClassChanged();
    partial void OncolHeadofClassContactChanging(string value);
    partial void OncolHeadofClassContactChanged();
    #endregion
		
		public tblClassDetail()
		{
			this._tblInstituteDetail = default(EntityRef<tblInstituteDetail>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_colClassId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int colClassId
		{
			get
			{
				return this._colClassId;
			}
			set
			{
				if ((this._colClassId != value))
				{
					this.OncolClassIdChanging(value);
					this.SendPropertyChanging();
					this._colClassId = value;
					this.SendPropertyChanged("colClassId");
					this.OncolClassIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_colClassName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string colClassName
		{
			get
			{
				return this._colClassName;
			}
			set
			{
				if ((this._colClassName != value))
				{
					this.OncolClassNameChanging(value);
					this.SendPropertyChanging();
					this._colClassName = value;
					this.SendPropertyChanged("colClassName");
					this.OncolClassNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_colInstituteId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int colInstituteId
		{
			get
			{
				return this._colInstituteId;
			}
			set
			{
				if ((this._colInstituteId != value))
				{
					if (this._tblInstituteDetail.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncolInstituteIdChanging(value);
					this.SendPropertyChanging();
					this._colInstituteId = value;
					this.SendPropertyChanged("colInstituteId");
					this.OncolInstituteIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_colHeadofClass", DbType="VarChar(50)")]
		public string colHeadofClass
		{
			get
			{
				return this._colHeadofClass;
			}
			set
			{
				if ((this._colHeadofClass != value))
				{
					this.OncolHeadofClassChanging(value);
					this.SendPropertyChanging();
					this._colHeadofClass = value;
					this.SendPropertyChanged("colHeadofClass");
					this.OncolHeadofClassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_colHeadofClassContact", DbType="NVarChar(50)")]
		public string colHeadofClassContact
		{
			get
			{
				return this._colHeadofClassContact;
			}
			set
			{
				if ((this._colHeadofClassContact != value))
				{
					this.OncolHeadofClassContactChanging(value);
					this.SendPropertyChanging();
					this._colHeadofClassContact = value;
					this.SendPropertyChanged("colHeadofClassContact");
					this.OncolHeadofClassContactChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblInstituteDetail_tblClassDetail", Storage="_tblInstituteDetail", ThisKey="colInstituteId", OtherKey="colInstituteId", IsForeignKey=true)]
		public tblInstituteDetail tblInstituteDetail
		{
			get
			{
				return this._tblInstituteDetail.Entity;
			}
			set
			{
				tblInstituteDetail previousValue = this._tblInstituteDetail.Entity;
				if (((previousValue != value) 
							|| (this._tblInstituteDetail.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblInstituteDetail.Entity = null;
						previousValue.tblClassDetails.Remove(this);
					}
					this._tblInstituteDetail.Entity = value;
					if ((value != null))
					{
						value.tblClassDetails.Add(this);
						this._colInstituteId = value.colInstituteId;
					}
					else
					{
						this._colInstituteId = default(int);
					}
					this.SendPropertyChanged("tblInstituteDetail");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class GetInstituteDetailsResult
	{
		
		private string _colInstitutename;
		
		private string _colAddress;
		
		private string _colPhone;
		
		private string _colLogoPath;
		
		private string _colPrincipalName;
		
		private string _colPrincipalContact;
		
		private string _colInstituteType;
		
		private string _colUsername;
		
		private string _colDistrict;
		
		private string _colState;
		
		public GetInstituteDetailsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_colInstitutename", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string colInstitutename
		{
			get
			{
				return this._colInstitutename;
			}
			set
			{
				if ((this._colInstitutename != value))
				{
					this._colInstitutename = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_colAddress", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string colAddress
		{
			get
			{
				return this._colAddress;
			}
			set
			{
				if ((this._colAddress != value))
				{
					this._colAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_colPhone", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string colPhone
		{
			get
			{
				return this._colPhone;
			}
			set
			{
				if ((this._colPhone != value))
				{
					this._colPhone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_colLogoPath", DbType="VarChar(50)")]
		public string colLogoPath
		{
			get
			{
				return this._colLogoPath;
			}
			set
			{
				if ((this._colLogoPath != value))
				{
					this._colLogoPath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_colPrincipalName", DbType="VarChar(50)")]
		public string colPrincipalName
		{
			get
			{
				return this._colPrincipalName;
			}
			set
			{
				if ((this._colPrincipalName != value))
				{
					this._colPrincipalName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_colPrincipalContact", DbType="NVarChar(50)")]
		public string colPrincipalContact
		{
			get
			{
				return this._colPrincipalContact;
			}
			set
			{
				if ((this._colPrincipalContact != value))
				{
					this._colPrincipalContact = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_colInstituteType", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string colInstituteType
		{
			get
			{
				return this._colInstituteType;
			}
			set
			{
				if ((this._colInstituteType != value))
				{
					this._colInstituteType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_colUsername", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string colUsername
		{
			get
			{
				return this._colUsername;
			}
			set
			{
				if ((this._colUsername != value))
				{
					this._colUsername = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_colDistrict", DbType="VarChar(50)")]
		public string colDistrict
		{
			get
			{
				return this._colDistrict;
			}
			set
			{
				if ((this._colDistrict != value))
				{
					this._colDistrict = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_colState", DbType="VarChar(50)")]
		public string colState
		{
			get
			{
				return this._colState;
			}
			set
			{
				if ((this._colState != value))
				{
					this._colState = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
